### ISSUE TITLE
error when imputing

### ISSUE THREAD

**Issue by MichelMoser** [StefanReuscher/ABHgenotypeR#5]
Dear Stefan, 

I try to use your function to impute a map object created with ASMap. 

when excuting the imputation, i get following error: 

postImpGenotypes <- imputeByFlanks(genotypes)
Error in 1:nrow(geno_temp) : argument of length 0

Could you help me with that? 
Thank you, 
Michel

**Comment by StefanReuscher** [comment]
Dear Michel,

Our package and ASMap use two different object structures. I dont know how ASMap objects look like. To make our package work follow the vignette, which starts with a genotype file in ABH format as described. If you feel confident enough you might also convert ASMap to our genotype object, which is just a named list. But that might be more difficult. I would export from ASMap, create file that can be read by ABHgenotypeR and then impute.

Gruß,

Stefan
